#!/bin/sh
export PATH=$PWD/node_modules/karma/bin:$PATH

./generate.py -sI test-source
php -S 0.0.0.0:31323 -t .. &> /dev/null &
sleep 3

karma start --reporters=dots,saucelabs --browsers=$1 --hostname="$(hostname)"
RET=$?

pkill -f 'php -S 0.0.0.0:31323' &> /dev/null
exit $RET
